# 7z a zip/class-py.zip cookiecutters/class-py
# 7z a zip/dash-app.zip cookiecutters/dash-app
# 7z a zip/dash-widget.zip cookiecutters/dash-widget
# 7z a zip/journal-project-tex.zip cookiecutters/journal-project-tex
# 7z a zip/poetry-click-app.zip cookiecutters/poetry-click-app
# 7z a zip/poetry-dash-app-simple.zip cookiecutters/poetry-dash-app-simple
# 7z a zip/poetry-dash-app-data.zip cookiecutters/poetry-dash-app-data
# 7z a zip/poetry-orange-widget.zip cookiecutters/poetry-orange-widget
# 7z a zip/pytorch-lstm-time-series.zip cookiecutters/pytorch-lstm-time-series